# This file deploys Firebase Functions when changes are merged into the master branch

name: Deploy Firebase Functions on merge

on:
  push:
    branches:
      - master

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./services
        run: npm install

      - name: Run tests
        working-directory: ./services
        run: npm run test

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions
        working-directory: ./services
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        run: firebase deploy --only functions